### ISSUE TITLE
完善文档和一个潜在的 bug

### ISSUE THREAD

**Issue by feitian124** [hubcarl/egg-webpack#1]
1. 仅使用普通的 ejs，jade 等作为模板引擎，该怎么使用你这个插件呢？能加个小例子吗？

2.  egg-webpack/lib/index.js 下面这个 hot middleware 是不是写错了？
```js
exports['koa-webpack-hot-middleware'] = require('koa-webpack-dev-middleware');
exports['koa-webpack-dev-middleware'] = require('koa-webpack-dev-middleware');
```

**Comment by jacksky007** [comment]
@feitian124 
1. 我估计你需要参考  [egg-view-vue-ssr](https://github.com/hubcarl/egg-view-vue-ssr) 和 [egg-webpack-vue](https://github.com/hubcarl/egg-webpack-vue) 相关内容
2. 两个 exports 好像并没有被使用，所以应该是 dead code
