### ISSUE TITLE
无法处理从内存里取出的mp4

### ISSUE THREAD

**Issue by blue080** [hubcarl/egg-webpack#10]
https://github.com/hubcarl/egg-webpack/blob/master/lib/utils.js#L17
这一行把图片以外的buffer全部utf8了，
建议直接放开，不处理，由上层处理buffer

**Comment by hubcarl** [comment]
目前，静态资源不再通过读取方式获取，只有读取文件内容时才通过该方法读取，只通过 koa-proxy 代理处理 https://github.com/easy-team/egg-webpack/blob/15e3efab51ee181baa1434a6f8f50d85a93a466e/lib/proxy.js
