### ISSUE TITLE
前端页面热更新无效！

### ISSUE THREAD

**Issue by Stanlous** [hubcarl/egg-webpack#11]
单独使用egg-webpack，修改前端页面文件，webpack自动编译了，但是没有热更新，前端页面没有自动更新修改。
情况一：只使用koa-webpack-dev-middleware和koa-webpack-hot-middleware，修改前端页面文件，webpack自动编译了，而且自动热更新前端页面。`热更新有效！`
egg里的app.js内容如下：
```js
const webpack = require('webpack')
const webpackDevMiddleware = require('koa-webpack-dev-middleware')
const webpacHotMiddleware = require('koa-webpack-hot-middleware')
const IS_PRODUCTION = process.env.NODE_ENV == 'production'
const devConfig = require('../config/webpack/webpack.dev.js')
const prodConfig = require('../config/webpack/webpack.prod.js')
const config = IS_PRODUCTION ? prodConfig : devConfig
const compiler = webpack(config)

module.exports = app => {
  app.beforeStart(async () => {
    app.use(webpackDevMiddleware(compiler, {
      publicPath: config.output.publicPath
    }))
    app.use(webpacHotMiddleware(compiler))
  })
}
```

情况二：删除上面的app.js，只启用egg-webpack（按照README.md里的说明）,修改了前端页面文件，webpack自动编译了，但没有热更新前端页面。`热更新无效！`
 {app_root}/config/config.default.js
```js
exports.webpack = {
  webpackConfigList: [require('../../config/webpack/webpack.dev.js')]
}
```

**Comment by muzi131313** [comment]
同问

**Comment by hubcarl** [comment]
@Stanlous @muzi131313   egg-webpack 需要增加如下配置

```bash
// ${root}/config/config.local.js
config.webpack = {
  hot: true
}
```

**Comment by fakership** [comment]
@muzi131313 你的改了hot: true就ok了么，我这边貌似没启效果，是因为webapck4么

**Comment by hubcarl** [comment]
单独使用 egg-webpack 时，需要在webpack 的 entry 加上 https://github.com/webpack-contrib/webpack-hot-middleware  配置 webpack-hot-middleware/client

**Comment by keenwon** [comment]
我写了个示例，有需要的朋友可以参考：https://github.com/keenwon/Egg-Webpack-Starter
