### ISSUE TITLE
此项目是否还在维护？

### ISSUE THREAD

**Issue by keenwon** [hubcarl/egg-webpack#17]
#11 #13 #15 #16

热更新的问题我也遇到了，并没有看到文档和 Issue 里有什么解决方案，请问此项目是否还在维护？

**Comment by hubcarl** [comment]
@keenwon  还在维护，  单独使用 egg-webpack 时， 需要在webpack 的 entry 加上 https://github.com/webpack-contrib/webpack-hot-middleware 配置 webpack-hot-middleware/client

可以参考 easywebpack 底层处理方式： https://github.com/easy-team/easywebpack/blob/master/lib/target/client.js#L67

**Comment by hubcarl** [comment]
单独使用方案： https://www.yuque.com/easy-team/egg-vue/version

**Comment by keenwon** [comment]
我添加了 webpack-hot-middleware，但是 __webpack_hmr 404，要自己处理？

**Comment by keenwon** [comment]
@hubcarl

搞定了，感谢。建议完善下文档。你给的单独使用的方案，感觉参考价值不大。我是看 [这个](https://github.com/easy-team/webpack-tool/blob/90a5a18bc0cf4556da6b905647d821e19a648a19/lib/utils.js#L72) 搞定的。

**Comment by keenwon** [comment]
我写了个示例，有需要的朋友可以参考：https://github.com/keenwon/Egg-Webpack-Starter
