### ISSUE TITLE
请问如何开启Gzip压缩？

### ISSUE THREAD

**Issue by iamnotblank** [hubcarl/egg-webpack#18]
### 版本：weback 3 
我在webpack.config.devServer 和app.config.webpack都尝试增加了 commress 配置，依然不起作用。

**Comment by hubcarl** [comment]
@iamnotblank  egg 项目请通过 egg-static 开启 gzip

**Comment by iamnotblank** [comment]
@hubcarl 我的意思是通过egg-webpack编译，开发环境的静态资源，你有点答非所问哦

**Comment by hubcarl** [comment]
@iamnotblank  开发环境目前不支持 gzip， 发布模式通过 egg-static 支持

**Comment by hubcarl** [comment]
开发环境暂不没有计划支持 gzip

**Comment by Kchen2017** [comment]
> ### 版本：weback 3
> 我在webpack.config.devServer 和app.config.webpack都尝试增加了 commress 配置，依然不起作用。

const compress = require('koa-compress');
<img width="743" alt="image" src="https://user-images.githubusercontent.com/32404881/163534217-3a0da4bb-23a2-479c-976d-930ff9c1b953.png">

这个插件本质上是起了一个koa，手写个中间件吧
