### ISSUE TITLE
Utils.readWebpackMemoryFile传了3个参数是bug吗

### ISSUE THREAD

**Issue by Imprevia** [hubcarl/egg-webpack#19]
https://github.com/easy-team/egg-webpack/blob/master/lib/server.js#L42
上面代码的Utils.readWebpackMemoryFile(compilers, filePath, data.fileName);传了3个参数。

https://github.com/easy-team/egg-webpack/blob/master/lib/utils.js#L5
这里的exports.readWebpackMemoryFile = (compiler, filePath)  只接收两个参数，这是bug吗

**Comment by hubcarl** [comment]
@Imprevia  这个不影响，这个参数没有用到，后面处理一下
