### ISSUE TITLE
proxy中间件会因为自定义的auth插件导致鉴权失败无法进行代理跳转

### ISSUE THREAD

**Issue by SingleMai** [hubcarl/egg-webpack#21]
在新版本(easy-webpack4.0)后，`egg-webpack` 中将 `proxy` 中间件从原来插入到中间件首位的方式更换为插入到中间件后方。
https://github.com/easy-team/egg-webpack/blob/master/app.js?1570629460961#L37
 
因此会导致应用在自定义了 auth 等鉴权插件时并不能顺利地进行proxy跳转导致鉴权报错。目前处理方式只能在 auth中间件中进行过滤判断。请问这样的改动是为了解决什么问题，而我遇到的问题有更好的解决方式么？

**Comment by hubcarl** [comment]
@SingleMai  egg-webpack 只会对 webpack 静态资源代理转发，你 auth 怎么会走到这里面来呢？

**Comment by SingleMai** [comment]
如图，这是正常情况下，egg的中间件列表即  `app.middleware` 的打印，从 `beginRequest` 开始是自定义的插件，其中会包含一个统一的鉴权中间件`authUser`
![image](https://user-images.githubusercontent.com/24849554/66543807-f7ead800-eb68-11e9-9844-d5efa2b038a9.png)

而本地运行时，我在`egg-webpack`的`app.js`操作中间件的位置进行打印后，发现`proxy`中间件是插入在 `authUser`之后，
![image](https://user-images.githubusercontent.com/24849554/66543848-15b83d00-eb69-11e9-99fc-03ba4d20860f.png)

我个人的理解是 实际上是因为 proxy 顺序在我的鉴权中间件之后，导致请求并未进入 egg-webpack 定义的中间件请求就被抛错出去导致的无法正常代理转发

**Comment by hubcarl** [comment]
@SingleMai  这个插件只在本地使用，你先过滤解决问题吧，这个需要再评估一下

**Comment by SingleMai** [comment]
嗯嗯 了解的。本地已经过滤掉了，其实主要是想了解一下从后面插入这个写法是有什么考虑么。。我百思不得其解...
