### ISSUE TITLE
how to use style-resources-loader 

### ISSUE THREAD

**Issue by super918180** [hubcarl/egg-webpack#22]
`
// webpack.config.js
module: {
        rules: [{
            test: /\.scss$/,
            use: ['style-loader', 'css-loader', 'sass-loader', {
                loader: 'style-resources-loader',
                options: {
                    patterns: [
                        path.resolve(__dirname, 'path/to/scss/variables/*.scss'),
                        path.resolve(__dirname, 'path/to/scss/mixins/*.scss'),
                    ]
                }
            }]
        }]
    },
`

![image](https://user-images.githubusercontent.com/20025505/67486212-31a9fb80-f69e-11e9-87ba-3d8450b76acb.png)

**Comment by hubcarl** [comment]
issue repeat https://github.com/easy-team/egg-vue-webpack-boilerplate/issues/132
