### ISSUE TITLE
Can't access static files in '/app/public' when enable egg-webpack

### ISSUE THREAD

**Issue by sanmaopep** [hubcarl/egg-webpack#3]
Before I enable egg-webpack I can access my css through http://127.0.0.1:7001/public/css/main.css.
But after I enable egg-webpack in plugin.local.js, add a webpack.config.js to webpackConfigList,I can't access http://127.0.0.1:7001/public/css/main.css(it returns 200 but empty content).
I can't work it out so I look for some help here.
Thx!

**Comment by hubcarl** [comment]
@sanmaopep latest version had fixed, you can try.   local mode , the file read from memory,  when file not exist,  the request will next eggjs process.
