### ISSUE TITLE
please set [egg-webpack] plugin config.module

### ISSUE THREAD

**Issue by jazzysnail** [hubcarl/egg-webpack#5]
请问 `egg-webpack` 一定需要 `easywebpack-${framework}` 来配合使用吗？单独使用 `egg-webpack` 时
`webpackConfigList` 已正确传入，但是报错 `please set [egg-webpack] plugin config.module`。

**Comment by hubcarl** [comment]
该问题已修复， 如果配置了 webpackConfigList 就不依赖 easywebpack

**Comment by nianiaJR** [comment]
为什么一直在报：
```please set [egg-webpack] plugin config.framework```
