### ISSUE TITLE
请问下这个插件只支持Egg1.x么？另外 视图（html、tpl)文件怎么调用内存中编译后的js文件？

### ISSUE THREAD

**Issue by wteam-xq** [hubcarl/egg-webpack#9]
根据Egg官网教程， `egg-init egg-example --type=simple` 生成 Egg2.x的脚手架；
配上webpack 3.x， 使用上这个插件发现修改了文件 命令窗口提示 编译成功， 然后 编译后的js文件没变化。 通过webpack-dev-server 教程了解到编译成功后的文件并没写入磁盘而是放在内存中。
所以有两个疑问：

1.插件只支持Egg1.x么？
看到`egg-webpack/package.json` 中：
> "egg": "^1.0.0",

2.怎么调用编译成功后放在内存中的 js ？
README.md 中自定义中部分： 下述代码在Egg工程中哪个文件写的？
```
app.webpack.fileSystem.readWebpackMemoryFile(filePath).then(fileContent =>{

})
```
顺便问下，可以设置成 编译后文件不放内存 而是 写入磁盘么？

**Comment by hubcarl** [comment]
egg-webpack 是内存编译，不落地磁盘， 内容获取具体看：https://yuque.com/hubcarl/ves/build

- 插件 支持 1.0 和 2.0 ， package.json 是 dev 的，用于测试的
- 代码写在 你需要获取文件内容的代码的地方，比如controller
